name: Checkout Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        run: actions/checkout@v4

      - name: print current directory
        run: pwd

      - name: List Repository Files
        run: ls -la

      - name: Display app.txt
        run:  cat app.txt
